Product.create!(name: "Settlers of Catan", price: 29.95)
Product.create!(name: "Technodrome", price: 27.99)
Product.create!(name: "Oh's Cereal", price: 3.95)
Product.create!(name: "RailsCasts Pro Subscription", price: 9.00)
Product.create!(name: "Flux Capacitor", price: 19.55)
Product.create!(name: "Rack", price: 32.49)
Product.create!(name: "Model Enterprise", price: 27.99)
Product.create!(name: "Agricola", price: 45.99)
Product.create!(name: "Millennium Falcon", price: 3597281000.00)
Product.create!(name: "Answer to Everything", price: 42.00)
Product.create!(name: "1000 Piece Jigsaw Puzzle", price: 14.99)
Product.create!(name: "CanCan Music Record", price: 2.99)
