electronics = Category.create!(name: "Electronics")
toys = Category.create!(name: "Toys & Games")
clothes = Category.create!(name: "Clothes")
furniture = Category.create!(name: "Furniture")
foods = Category.create!(name: "Foods")

Product.create!(stock: 5, name: "Settlers of Catan", price: 34.95, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "Red Shirt", price: 12.49, released_at: rand(1..90).days.ago, category_id: clothes.id)
Product.create!(stock: 5, name: "Oak Coffee Table", price: 223.99, released_at: rand(1..90).days.ago, category_id: furniture.id)
Product.create!(stock: 5, name: "Technodrome", price: 27.99, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "Oh's Cereal", price: 3.95, released_at: rand(1..90).days.ago, category_id: foods.id)
Product.create!(stock: 5, name: "Game Console", price: 299.95, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "Video Game", price: 29.95, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "Lawn Chair", price: 34.99, released_at: rand(1..90).days.ago, category_id: furniture.id)
Product.create!(stock: 1, name: "Dog Toy Bone", price: 2.99, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "Heated Blanket", price: 27.95, released_at: 10.days.from_now, category_id: furniture.id)
Product.create!(stock: 5, name: "Flux Capacitor", price: 19.55, released_at: rand(1..90).days.ago, category_id: electronics.id)
Product.create!(stock: 1, name: "Chocolate Pie", price: 3.14, released_at: rand(1..90).days.ago, category_id: foods.id)
Product.create!(stock: 5, name: "Acoustic Guitar", price: 1025.00, released_at: rand(1..90).days.ago, category_id: electronics.id, discontinued_at: 5.days.ago)
Product.create!(stock: 5, name: "Model Enterprise", price: 27.99, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "Agricola", price: 45.99, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "Stone Age", price: 34.99, released_at: 15.days.from_now, category_id: toys.id)
Product.create!(stock: 5, name: "7 Wonders", price: 28.75, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "Seafarers of Catan", price: 19.95, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "Knights of Catan", price: 19.95, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "Starfarers of Catan", price: 19.95, released_at: 90.days.ago, discontinued_at: 2.days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "Millennium Falcon", price: 3597200.00, released_at: rand(1..90).days.ago, category_id: electronics.id)
Product.create!(stock: 5, name: "Answer to Everything", price: 42.00, released_at: rand(1..90).days.ago, category_id: electronics.id)
Product.create!(stock: 5, name: "Box Kite", price: 63.00, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 0, name: "1000 Piece Jigsaw Puzzle", price: 14.99, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "Rubber Ducky", price: 4.75, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "Unicorn Action Figure", price: 8.75, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "Rack", price: 32.49, released_at: rand(1..90).days.ago, category_id: furniture.id)
Product.create!(stock: 5, name: "Model Train Rails", price: 45.00, released_at: rand(1..90).days.ago, category_id: toys.id)
Product.create!(stock: 5, name: "CanCan Music Record", price: 2.99, released_at: rand(1..90).days.ago, category_id: electronics.id)
