Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Settlers of Catan", price: 34.99, released_at: "2011-07-15")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Seafarers of Catan", price: 34.99, released_at: "2011-07-15")
Product.create!(category: Category.find_or_create_by_name("Electronics"), name: "DVD Player", price: 79.99, released_at: "2011-07-18")
Product.create!(category: Category.find_or_create_by_name("Clothing"), name: "Red Shirt", price: 12.49)
Product.create!(category: Category.find_or_create_by_name("Furniture"), name: "Black Leather Couch", price: 399.99)
Product.create!(category: Category.find_or_create_by_name("Furniture"), name: "Oak Coffee Table", price: 223.99, released_at: "2011-07-28")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Technodrome", price: 27.99, released_at: "2011-07-28")
Product.create!(category: Category.find_or_create_by_name("Food"), name: "Oh's Cereal", price: 3.95)
Product.create!(category: Category.find_or_create_by_name("Electronics"), name: "Game Console", price: 299.95, released_at: "2011-08-02")
Product.create!(category: Category.find_or_create_by_name("Electronics"), name: "Video Game", price: 29.95, released_at: "2011-08-05")
Product.create!(category: Category.find_or_create_by_name("Furniture"), name: "Lawn Chair", price: 34.99, released_at: "2011-08-05")
Product.create!(category: Category.find_or_create_by_name("Electronics"), name: "RailsCasts Pro Subscription", price: 9.00, released_at: "2011-10-03")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Dog Toy Bone", price: 2.99, released_at: "2011-08-08")
Product.create!(category: Category.find_or_create_by_name("Furniture"), name: "Heated Blanket", price: 27.95, released_at: "2011-08-09")
Product.create!(category: Category.find_or_create_by_name("Electronics"), name: "Flux Capacitor", price: 19.55, released_at: "2011-08-12")
Product.create!(category: Category.find_or_create_by_name("Misc"), name: "Plutonium", price: 2397.25, released_at: "2011-08-18")
Product.create!(category: Category.find_or_create_by_name("Food"), name: "Chocolate Pie", price: 3.14, released_at: "2011-03-14")
Product.create!(category: Category.find_or_create_by_name("Food"), name: "Ryan's Cheesecake", price: 49.99, released_at: "2011-08-22")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Acoustic Guitar", price: 1025.00, released_at: "2011-08-23")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Model Enterprise", price: 27.99, released_at: "2011-08-27")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Agricola", price: 45.99, released_at: "2011-08-28")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Stone Age", price: 34.99, released_at: "2011-08-30")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "7 Wonders", price: 28.75)
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Millennium Falcon", price: 3597281000.00, released_at: "2011-09-07")
Product.create!(category: Category.find_or_create_by_name("Misc"), name: "Answer to Everything", price: 42.00, released_at: "2011-09-08")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Box Kite", price: 63.00, released_at: "2011-09-10")
Product.create!(category: Category.find_or_create_by_name("Misc"), name: "Phil's Painting", price: 399.00, released_at: "2011-09-14")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "1000 Piece Jigsaw Puzzle", price: 14.99, released_at: "2011-09-17")
Product.create!(category: Category.find_or_create_by_name("Electronics"), name: "TextMate 2", price: 75.00, released_at: "2011-09-22")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Bowling Ball", price: 127.00, released_at: "2011-09-23")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Rubber Ducky", price: 4.75, released_at: "2011-09-25")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Unicorn Action Figure", price: 8.75, released_at: "2011-09-25")
Product.create!(category: Category.find_or_create_by_name("Hardware"), name: "Rack", price: 32.49, released_at: "2011-09-28")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Model Train Rails", price: 45.00, released_at: "2011-10-01")
Product.create!(category: Category.find_or_create_by_name("Electronics"), name: "CanCan Music Record", price: 2.99, released_at: "2011-10-04")
