source 'http://rubygems.org'

gem 'rails', '3.1.0'
gem 'sqlite3'
gem 'nifty-generators'
gem 'jquery-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end


